# Imports

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import plotly.express as px

# Data Exploration

In [4]:
raw_data_df = pd.read_csv("/content/demanddata_2025.csv")

In [5]:
print(f"Shape of raw data: {raw_data_df.shape}")

Shape of raw data: (17520, 22)

In [6]:
print(f"Columns of raw data: {raw_data_df.columns}")

Columns of raw data: Index(['SETTLEMENT_DATE', 'SETTLEMENT_PERIOD', 'ND', 'TSD',
       'ENGLAND_WALES_DEMAND', 'EMBEDDED_WIND_GENERATION',
       'EMBEDDED_WIND_CAPACITY', 'EMBEDDED_SOLAR_GENERATION',
       'EMBEDDED_SOLAR_CAPACITY', 'NON_BM_STOR', 'PUMP_STORAGE_PUMPING',
       'SCOTTISH_TRANSFER', 'IFA_FLOW', 'IFA2_FLOW', 'BRITNED_FLOW',
       'MOYLE_FLOW', 'EAST_WEST_FLOW', 'NEMO_FLOW', 'NSL_FLOW',
       'ELECLINK_FLOW', 'VIKING_FLOW', 'GREENLINK_FLOW'],
      dtype='object')

In [7]:
raw_data_df.head()

,SETTLEMENT_DATE,SETTLEMENT_PERIOD,ND,TSD,ENGLAND_WALES_DEMAND,EMBEDDED_WIND_GENERATION,EMBEDDED_WIND_CAPACITY,EMBEDDED_SOLAR_GENERATION,EMBEDDED_SOLAR_CAPACITY,NON_BM_STOR,...,IFA_FLOW,IFA2_FLOW,BRITNED_FLOW,MOYLE_FLOW,EAST_WEST_FLOW,NEMO_FLOW,NSL_FLOW,ELECLINK_FLOW,VIKING_FLOW,GREENLINK_FLOW
0,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,0,...,-1518,-1026,1,-232,-386,-558,96,0,241,0
1,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,0,...,-1513,-1023,1,-124,-282,-564,51,0,262,0
2,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,0,...,-1428,-922,1,-119,-384,-205,62,0,414,0
3,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,0,...,-1423,-915,0,-119,-334,-193,37,0,423,0
4,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,0,...,-1539,-899,0,-119,-363,-622,-282,0,288,0

In [8]:
raw_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17520 entries, 0 to 17519
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   SETTLEMENT_DATE            17520 non-null  object
 1   SETTLEMENT_PERIOD          17520 non-null  int64
 2   ND                         17520 non-null  int64
 3   TSD                        17520 non-null  int64
 4   ENGLAND_WALES_DEMAND       17520 non-null  int64
 5   EMBEDDED_WIND_GENERATION   17520 non-null  int64
 6   EMBEDDED_WIND_CAPACITY     17520 non-null  int64
 7   EMBEDDED_SOLAR_GENERATION  17520 non-null  int64
 8   EMBEDDED_SOLAR_CAPACITY    17520 non-null  int64
 9   NON_BM_STOR                17520 non-null  int64
 10  PUMP_STORAGE_PUMPING       17520 non-null  int64
 11  SCOTTISH_TRANSFER          17520 non-null  int64
 12  IFA_FLOW                   17520 non-null  int64
 13  IFA2_FLOW                  17520 non-null  int64
 14  BRITNED_FLOW               17520 non-null  int64
 15  MOYLE_FLOW                 17520 non-null  int64
 16  EAST_WEST_FLOW             17520 non-null  int64
 17  NEMO_FLOW                  17520 non-null  int64
 18  NSL_FLOW                   17520 non-null  int64
 19  ELECLINK_FLOW              17520 non-null  int64
 20  VIKING_FLOW                17520 non-null  int64
 21  GREENLINK_FLOW             17520 non-null  int64
dtypes: int64(21), object(1)
memory usage: 2.9+ MB

In [9]:
raw_data_df.isna().sum()

SETTLEMENT_DATE              0
SETTLEMENT_PERIOD            0
ND                           0
TSD                          0
ENGLAND_WALES_DEMAND         0
EMBEDDED_WIND_GENERATION     0
EMBEDDED_WIND_CAPACITY       0
EMBEDDED_SOLAR_GENERATION    0
EMBEDDED_SOLAR_CAPACITY      0
NON_BM_STOR                  0
PUMP_STORAGE_PUMPING         0
SCOTTISH_TRANSFER            0
IFA_FLOW                     0
IFA2_FLOW                    0
BRITNED_FLOW                 0
MOYLE_FLOW                   0
EAST_WEST_FLOW               0
NEMO_FLOW                    0
NSL_FLOW                     0
ELECLINK_FLOW                0
VIKING_FLOW                  0
GREENLINK_FLOW               0
dtype: int64

In [10]:
raw_data_df.describe().T

,count,mean,std,min,25%,50%,75%,max
SETTLEMENT_PERIOD,17520.0,24.500228,13.854190,1.0,12.75,24.5,36.25,50.0
ND,17520.0,26158.072603,6172.933513,12803.0,21432.75,24960.0,29825.25,45924.0
TSD,17520.0,28563.251256,6107.866569,15297.0,23897.75,27269.0,32193.25,47760.0
ENGLAND_WALES_DEMAND,17520.0,23996.221975,5650.814832,12040.0,19638.00,22904.0,27386.25,41835.0
EMBEDDED_WIND_GENERATION,17520.0,1951.346233,1279.663725,125.0,927.00,1604.0,2756.00,5922.0
EMBEDDED_WIND_CAPACITY,17520.0,6606.000000,0.000000,6606.0,6606.00,6606.0,6606.00,6606.0
EMBEDDED_SOLAR_GENERATION,17520.0,2130.222374,3281.983315,0.0,0.00,7.0,3483.00,14046.0
EMBEDDED_SOLAR_CAPACITY,17520.0,20813.171233,840.120108,19270.0,20179.00,20988.0,21510.00,22126.0
NON_BM_STOR,17520.0,0.000228,0.021368,0.0,0.00,0.0,0.00,2.0
PUMP_STORAGE_PUMPING,17520.0,172.601199,318.518752,0.0,5.00,12.0,170.00,1739.0
SCOTTISH_TRANSFER,17520.0,2114.014384,1801.190544,-2012.0,716.75,2039.5,3595.25,6586.0
IFA_FLOW,17520.0,1179.809874,687.094268,-2071.0,978.75,1357.0,1510.00,2024.0
IFA2_FLOW,17520.0,651.980479,483.220995,-1028.0,254.00,984.0,992.00,1058.0
BRITNED_FLOW,17520.0,50.336358,723.071698,-1093.0,-592.00,0.0,783.00,1116.0
MOYLE_FLOW,17520.0,-254.829795,219.912302,-453.0,-451.00,-345.0,-35.00,400.0
EAST_WEST_FLOW,17520.0,-192.334532,237.632607,-532.0,-492.00,-48.0,0.00,504.0
NEMO_FLOW,17520.0,227.191610,676.693354,-1024.0,-305.00,348.0,886.00,1063.0
NSL_FLOW,17520.0,1022.861130,636.782911,-1453.0,916.00,1395.0,1397.00,1491.0
ELECLINK_FLOW,17520.0,672.369977,440.439194,-1023.0,218.00,991.0,996.00,1063.0
VIKING_FLOW,17520.0,290.206792,854.485430,-1453.0,-457.00,461.0,989.00,1428.0
GREENLINK_FLOW,17520.0,-321.298345,280.515292,-539.0,-514.00,-506.0,-137.75,506.0

In [11]:
raw_data_df[["ND", "TSD", "EMBEDDED_WIND_GENERATION","EMBEDDED_SOLAR_GENERATION"]].head()

      ND    TSD  EMBEDDED_WIND_GENERATION  EMBEDDED_SOLAR_GENERATION
0  21036  26215                      5405                          0
1  21222  26063                      5358                          0
2  21385  25734                      5237                          0
3  20473  24988                      5115                          0
4  19634  24912                      5080                          0

**Notes on section - Data Exploration**

ND - National Demand. GB metered generation requirement, exluding station load, pumped storage pumping and interconnector exports


TSD - ND + "station load, pump storage pumping and interconnector exports"


Embedded Wind/solar generation = estimated additional wind/solar being generated inside distribution networks.

https://www.neso.energy/data-portal/historic-demand-data/historic_demand_data_2025




Based on the functions ran above, there are no missing values. The number of rows are 17520.

Settlement Period 1 = 00:00 - 00:30.
Each period is a 30 min window

Settlemennt Period does have DST issue- 50 30min periods, instead of the 48

In [15]:

raw_data_df["SETTLEMENT_DATE"] = pd.to_datetime(raw_data_df["SETTLEMENT_DATE"])

In [29]:
delta_time =pd.to_timedelta((raw_data_df["SETTLEMENT_PERIOD"]-1)*30, unit = "min")
print(delta_time.head())

0   0 days 00:00:00
1   0 days 00:30:00
2   0 days 01:00:00
3   0 days 01:30:00
4   0 days 02:00:00
Name: SETTLEMENT_PERIOD, dtype: timedelta64[ns]

In [32]:
datetime = raw_data_df["SETTLEMENT_DATE"] + delta_time
raw_data_df["DATETIME"] = datetime

In [34]:
datetime_col = raw_data_df.pop("DATETIME")
raw_data_df.insert(0, "DATETIME", datetime_col)

In [35]:
raw_data_df.head()

,DATETIME,SETTLEMENT_DATE,SETTLEMENT_PERIOD,ND,TSD,ENGLAND_WALES_DEMAND,EMBEDDED_WIND_GENERATION,EMBEDDED_WIND_CAPACITY,EMBEDDED_SOLAR_GENERATION,EMBEDDED_SOLAR_CAPACITY,...,IFA_FLOW,IFA2_FLOW,BRITNED_FLOW,MOYLE_FLOW,EAST_WEST_FLOW,NEMO_FLOW,NSL_FLOW,ELECLINK_FLOW,VIKING_FLOW,GREENLINK_FLOW
0,2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,...,-1518,-1026,1,-232,-386,-558,96,0,241,0
1,2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,...,-1513,-1023,1,-124,-282,-564,51,0,262,0
2,2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,...,-1428,-922,1,-119,-384,-205,62,0,414,0
3,2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,...,-1423,-915,0,-119,-334,-193,37,0,423,0
4,2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,...,-1539,-899,0,-119,-363,-622,-282,0,288,0

In [ ]:
# DST issue

In [41]:
period_count = raw_data_df["SETTLEMENT_DATE"].value_counts().sort_index()

period_count[period_count !=48]

SETTLEMENT_DATE
2025-03-30    46
2025-10-26    50
Name: count, dtype: int64

In [45]:
model_time = pd.date_range(start="2025-01-01 00:00:00", periods=17520, freq="30min")

In [51]:
raw_data_df["MODEL TIME"] = model_time

In [52]:
raw_data_df.head()

,DATETIME,SETTLEMENT_DATE,SETTLEMENT_PERIOD,ND,TSD,ENGLAND_WALES_DEMAND,EMBEDDED_WIND_GENERATION,EMBEDDED_WIND_CAPACITY,EMBEDDED_SOLAR_GENERATION,EMBEDDED_SOLAR_CAPACITY,...,IFA2_FLOW,BRITNED_FLOW,MOYLE_FLOW,EAST_WEST_FLOW,NEMO_FLOW,NSL_FLOW,ELECLINK_FLOW,VIKING_FLOW,GREENLINK_FLOW,MODEL TIME
0,2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,...,-1026,1,-232,-386,-558,96,0,241,0,2025-01-01 00:00:00
1,2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,...,-1023,1,-124,-282,-564,51,0,262,0,2025-01-01 00:30:00
2,2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,...,-922,1,-119,-384,-205,62,0,414,0,2025-01-01 01:00:00
3,2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,...,-915,0,-119,-334,-193,37,0,423,0,2025-01-01 01:30:00
4,2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,...,-899,0,-119,-363,-622,-282,0,288,0,2025-01-01 02:00:00

In [53]:

raw_data_df.insert(0,"MODEL_TIME",model_time)

In [56]:
raw_data_df[["MODEL_TIME", "SETTLEMENT_DATE", "SETTLEMENT_PERIOD"]].head()

           MODEL_TIME SETTLEMENT_DATE  SETTLEMENT_PERIOD
0 2025-01-01 00:00:00      2025-01-01                  1
1 2025-01-01 00:30:00      2025-01-01                  2
2 2025-01-01 01:00:00      2025-01-01                  3
3 2025-01-01 01:30:00      2025-01-01                  4
4 2025-01-01 02:00:00      2025-01-01                  5

In [57]:
UTC = raw_data_df["MODEL_TIME"].dt.tz_localize("UTC")

In [58]:
raw_data_df.head()

,MODEL_TIME,DATETIME,SETTLEMENT_DATE,SETTLEMENT_PERIOD,ND,TSD,ENGLAND_WALES_DEMAND,EMBEDDED_WIND_GENERATION,EMBEDDED_WIND_CAPACITY,EMBEDDED_SOLAR_GENERATION,...,IFA2_FLOW,BRITNED_FLOW,MOYLE_FLOW,EAST_WEST_FLOW,NEMO_FLOW,NSL_FLOW,ELECLINK_FLOW,VIKING_FLOW,GREENLINK_FLOW,MODEL TIME
0,2025-01-01 00:00:00,2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,...,-1026,1,-232,-386,-558,96,0,241,0,2025-01-01 00:00:00
1,2025-01-01 00:30:00,2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,...,-1023,1,-124,-282,-564,51,0,262,0,2025-01-01 00:30:00
2,2025-01-01 01:00:00,2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,...,-922,1,-119,-384,-205,62,0,414,0,2025-01-01 01:00:00
3,2025-01-01 01:30:00,2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,...,-915,0,-119,-334,-193,37,0,423,0,2025-01-01 01:30:00
4,2025-01-01 02:00:00,2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,...,-899,0,-119,-363,-622,-282,0,288,0,2025-01-01 02:00:00

In [60]:
raw_data_df["MODEL_TIME"] = UTC

In [61]:
raw_data_df.head()

,MODEL_TIME,DATETIME,SETTLEMENT_DATE,SETTLEMENT_PERIOD,ND,TSD,ENGLAND_WALES_DEMAND,EMBEDDED_WIND_GENERATION,EMBEDDED_WIND_CAPACITY,EMBEDDED_SOLAR_GENERATION,...,IFA2_FLOW,BRITNED_FLOW,MOYLE_FLOW,EAST_WEST_FLOW,NEMO_FLOW,NSL_FLOW,ELECLINK_FLOW,VIKING_FLOW,GREENLINK_FLOW,MODEL TIME
0,2025-01-01 00:00:00+00:00,2025-01-01 00:00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,...,-1026,1,-232,-386,-558,96,0,241,0,2025-01-01 00:00:00
1,2025-01-01 00:30:00+00:00,2025-01-01 00:30:00,2025-01-01,2,21222,26063,20167,5358,6606,0,...,-1023,1,-124,-282,-564,51,0,262,0,2025-01-01 00:30:00
2,2025-01-01 01:00:00+00:00,2025-01-01 01:00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,...,-922,1,-119,-384,-205,62,0,414,0,2025-01-01 01:00:00
3,2025-01-01 01:30:00+00:00,2025-01-01 01:30:00,2025-01-01,4,20473,24988,19460,5115,6606,0,...,-915,0,-119,-334,-193,37,0,423,0,2025-01-01 01:30:00
4,2025-01-01 02:00:00+00:00,2025-01-01 02:00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,...,-899,0,-119,-363,-622,-282,0,288,0,2025-01-01 02:00:00

In [63]:
raw_data_df.drop(columns = ["DATETIME"], inplace = True)

In [64]:
raw_data_df["MODEL_TIME"].dtype

datetime64[ns, UTC]

In [65]:
check_period_count = raw_data_df["SETTLEMENT_DATE"].value_counts().sort_index()

check_period_count[period_count !=48]

SETTLEMENT_DATE
2025-03-30    46
2025-10-26    50
Name: count, dtype: int64

In [72]:
mask = raw_data_df["SETTLEMENT_DATE"] == pd.Timestamp("2025-03-30")

In [73]:
raw_data_df.loc[mask, ["MODEL_TIME", "SETTLEMENT_DATE","SETTLEMENT_PERIOD"]]

                    MODEL_TIME SETTLEMENT_DATE  SETTLEMENT_PERIOD
4224 2025-03-30 00:00:00+00:00      2025-03-30                  1
4225 2025-03-30 00:30:00+00:00      2025-03-30                  2
4226 2025-03-30 01:00:00+00:00      2025-03-30                  3
4227 2025-03-30 01:30:00+00:00      2025-03-30                  4
4228 2025-03-30 02:00:00+00:00      2025-03-30                  5
4229 2025-03-30 02:30:00+00:00      2025-03-30                  6
4230 2025-03-30 03:00:00+00:00      2025-03-30                  7
4231 2025-03-30 03:30:00+00:00      2025-03-30                  8
4232 2025-03-30 04:00:00+00:00      2025-03-30                  9
4233 2025-03-30 04:30:00+00:00      2025-03-30                 10
4234 2025-03-30 05:00:00+00:00      2025-03-30                 11
4235 2025-03-30 05:30:00+00:00      2025-03-30                 12
4236 2025-03-30 06:00:00+00:00      2025-03-30                 13
4237 2025-03-30 06:30:00+00:00      2025-03-30                 14
4238 2025-03-30 07:00:00+00:00      2025-03-30                 15
4239 2025-03-30 07:30:00+00:00      2025-03-30                 16
4240 2025-03-30 08:00:00+00:00      2025-03-30                 17
4241 2025-03-30 08:30:00+00:00      2025-03-30                 18
4242 2025-03-30 09:00:00+00:00      2025-03-30                 19
4243 2025-03-30 09:30:00+00:00      2025-03-30                 20
4244 2025-03-30 10:00:00+00:00      2025-03-30                 21
4245 2025-03-30 10:30:00+00:00      2025-03-30                 22
4246 2025-03-30 11:00:00+00:00      2025-03-30                 23
4247 2025-03-30 11:30:00+00:00      2025-03-30                 24
4248 2025-03-30 12:00:00+00:00      2025-03-30                 25
4249 2025-03-30 12:30:00+00:00      2025-03-30                 26
4250 2025-03-30 13:00:00+00:00      2025-03-30                 27
4251 2025-03-30 13:30:00+00:00      2025-03-30                 28
4252 2025-03-30 14:00:00+00:00      2025-03-30                 29
4253 2025-03-30 14:30:00+00:00      2025-03-30                 30
4254 2025-03-30 15:00:00+00:00      2025-03-30                 31
4255 2025-03-30 15:30:00+00:00      2025-03-30                 32
4256 2025-03-30 16:00:00+00:00      2025-03-30                 33
4257 2025-03-30 16:30:00+00:00      2025-03-30                 34
4258 2025-03-30 17:00:00+00:00      2025-03-30                 35
4259 2025-03-30 17:30:00+00:00      2025-03-30                 36
4260 2025-03-30 18:00:00+00:00      2025-03-30                 37
4261 2025-03-30 18:30:00+00:00      2025-03-30                 38
4262 2025-03-30 19:00:00+00:00      2025-03-30                 39
4263 2025-03-30 19:30:00+00:00      2025-03-30                 40
4264 2025-03-30 20:00:00+00:00      2025-03-30                 41
4265 2025-03-30 20:30:00+00:00      2025-03-30                 42
4266 2025-03-30 21:00:00+00:00      2025-03-30                 43
4267 2025-03-30 21:30:00+00:00      2025-03-30                 44
4268 2025-03-30 22:00:00+00:00      2025-03-30                 45
4269 2025-03-30 22:30:00+00:00      2025-03-30                 46

In [74]:
mask2 = raw_data_df["SETTLEMENT_DATE"] == pd.Timestamp("2025-10-26")

In [75]:
raw_data_df.loc[mask2, ["MODEL_TIME", "SETTLEMENT_DATE","SETTLEMENT_PERIOD"]]

                     MODEL_TIME SETTLEMENT_DATE  SETTLEMENT_PERIOD
14302 2025-10-25 23:00:00+00:00      2025-10-26                  1
14303 2025-10-25 23:30:00+00:00      2025-10-26                  2
14304 2025-10-26 00:00:00+00:00      2025-10-26                  3
14305 2025-10-26 00:30:00+00:00      2025-10-26                  4
14306 2025-10-26 01:00:00+00:00      2025-10-26                  5
14307 2025-10-26 01:30:00+00:00      2025-10-26                  6
14308 2025-10-26 02:00:00+00:00      2025-10-26                  7
14309 2025-10-26 02:30:00+00:00      2025-10-26                  8
14310 2025-10-26 03:00:00+00:00      2025-10-26                  9
14311 2025-10-26 03:30:00+00:00      2025-10-26                 10
14312 2025-10-26 04:00:00+00:00      2025-10-26                 11
14313 2025-10-26 04:30:00+00:00      2025-10-26                 12
14314 2025-10-26 05:00:00+00:00      2025-10-26                 13
14315 2025-10-26 05:30:00+00:00      2025-10-26                 14
14316 2025-10-26 06:00:00+00:00      2025-10-26                 15
14317 2025-10-26 06:30:00+00:00      2025-10-26                 16
14318 2025-10-26 07:00:00+00:00      2025-10-26                 17
14319 2025-10-26 07:30:00+00:00      2025-10-26                 18
14320 2025-10-26 08:00:00+00:00      2025-10-26                 19
14321 2025-10-26 08:30:00+00:00      2025-10-26                 20
14322 2025-10-26 09:00:00+00:00      2025-10-26                 21
14323 2025-10-26 09:30:00+00:00      2025-10-26                 22
14324 2025-10-26 10:00:00+00:00      2025-10-26                 23
14325 2025-10-26 10:30:00+00:00      2025-10-26                 24
14326 2025-10-26 11:00:00+00:00      2025-10-26                 25
14327 2025-10-26 11:30:00+00:00      2025-10-26                 26
14328 2025-10-26 12:00:00+00:00      2025-10-26                 27
14329 2025-10-26 12:30:00+00:00      2025-10-26                 28
14330 2025-10-26 13:00:00+00:00      2025-10-26                 29
14331 2025-10-26 13:30:00+00:00      2025-10-26                 30
14332 2025-10-26 14:00:00+00:00      2025-10-26                 31
14333 2025-10-26 14:30:00+00:00      2025-10-26                 32
14334 2025-10-26 15:00:00+00:00      2025-10-26                 33
14335 2025-10-26 15:30:00+00:00      2025-10-26                 34
14336 2025-10-26 16:00:00+00:00      2025-10-26                 35
14337 2025-10-26 16:30:00+00:00      2025-10-26                 36
14338 2025-10-26 17:00:00+00:00      2025-10-26                 37
14339 2025-10-26 17:30:00+00:00      2025-10-26                 38
14340 2025-10-26 18:00:00+00:00      2025-10-26                 39
14341 2025-10-26 18:30:00+00:00      2025-10-26                 40
14342 2025-10-26 19:00:00+00:00      2025-10-26                 41
14343 2025-10-26 19:30:00+00:00      2025-10-26                 42
14344 2025-10-26 20:00:00+00:00      2025-10-26                 43
14345 2025-10-26 20:30:00+00:00      2025-10-26                 44
14346 2025-10-26 21:00:00+00:00      2025-10-26                 45
14347 2025-10-26 21:30:00+00:00      2025-10-26                 46
14348 2025-10-26 22:00:00+00:00      2025-10-26                 47
14349 2025-10-26 22:30:00+00:00      2025-10-26                 48
14350 2025-10-26 23:00:00+00:00      2025-10-26                 49
14351 2025-10-26 23:30:00+00:00      2025-10-26                 50

In [77]:
raw_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17520 entries, 0 to 17519
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   MODEL_TIME                 17520 non-null  datetime64[ns, UTC]
 1   SETTLEMENT_DATE            17520 non-null  datetime64[ns]
 2   SETTLEMENT_PERIOD          17520 non-null  int64
 3   ND                         17520 non-null  int64
 4   TSD                        17520 non-null  int64
 5   ENGLAND_WALES_DEMAND       17520 non-null  int64
 6   EMBEDDED_WIND_GENERATION   17520 non-null  int64
 7   EMBEDDED_WIND_CAPACITY     17520 non-null  int64
 8   EMBEDDED_SOLAR_GENERATION  17520 non-null  int64
 9   EMBEDDED_SOLAR_CAPACITY    17520 non-null  int64
 10  NON_BM_STOR                17520 non-null  int64
 11  PUMP_STORAGE_PUMPING       17520 non-null  int64
 12  SCOTTISH_TRANSFER          17520 non-null  int64
 13  IFA_FLOW                   17520 non-null  int64
 14  IFA2_FLOW                  17520 non-null  int64
 15  BRITNED_FLOW               17520 non-null  int64
 16  MOYLE_FLOW                 17520 non-null  int64
 17  EAST_WEST_FLOW             17520 non-null  int64
 18  NEMO_FLOW                  17520 non-null  int64
 19  NSL_FLOW                   17520 non-null  int64
 20  ELECLINK_FLOW              17520 non-null  int64
 21  VIKING_FLOW                17520 non-null  int64
 22  GREENLINK_FLOW             17520 non-null  int64
 23  MODEL TIME                 17520 non-null  datetime64[ns]
dtypes: datetime64[ns, UTC](1), datetime64[ns](2), int64(21)
memory usage: 3.2 MB

In [78]:
raw_data_df.head()

,MODEL_TIME,SETTLEMENT_DATE,SETTLEMENT_PERIOD,ND,TSD,ENGLAND_WALES_DEMAND,EMBEDDED_WIND_GENERATION,EMBEDDED_WIND_CAPACITY,EMBEDDED_SOLAR_GENERATION,EMBEDDED_SOLAR_CAPACITY,...,IFA2_FLOW,BRITNED_FLOW,MOYLE_FLOW,EAST_WEST_FLOW,NEMO_FLOW,NSL_FLOW,ELECLINK_FLOW,VIKING_FLOW,GREENLINK_FLOW,MODEL TIME
0,2025-01-01 00:00:00+00:00,2025-01-01,1,21036,26215,19918,5405,6606,0,19270,...,-1026,1,-232,-386,-558,96,0,241,0,2025-01-01 00:00:00
1,2025-01-01 00:30:00+00:00,2025-01-01,2,21222,26063,20167,5358,6606,0,19270,...,-1023,1,-124,-282,-564,51,0,262,0,2025-01-01 00:30:00
2,2025-01-01 01:00:00+00:00,2025-01-01,3,21385,25734,20328,5237,6606,0,19270,...,-922,1,-119,-384,-205,62,0,414,0,2025-01-01 01:00:00
3,2025-01-01 01:30:00+00:00,2025-01-01,4,20473,24988,19460,5115,6606,0,19270,...,-915,0,-119,-334,-193,37,0,423,0,2025-01-01 01:30:00
4,2025-01-01 02:00:00+00:00,2025-01-01,5,19634,24912,18654,5080,6606,0,19270,...,-899,0,-119,-363,-622,-282,0,288,0,2025-01-01 02:00:00

In [79]:
raw_data_df.columns[raw_data_df.columns.duplicated()]

Index([], dtype='object')

In [80]:
raw_data_df.drop(columns = ["MODEL TIME"], inplace = True)

In [81]:
raw_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17520 entries, 0 to 17519
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   MODEL_TIME                 17520 non-null  datetime64[ns, UTC]
 1   SETTLEMENT_DATE            17520 non-null  datetime64[ns]
 2   SETTLEMENT_PERIOD          17520 non-null  int64
 3   ND                         17520 non-null  int64
 4   TSD                        17520 non-null  int64
 5   ENGLAND_WALES_DEMAND       17520 non-null  int64
 6   EMBEDDED_WIND_GENERATION   17520 non-null  int64
 7   EMBEDDED_WIND_CAPACITY     17520 non-null  int64
 8   EMBEDDED_SOLAR_GENERATION  17520 non-null  int64
 9   EMBEDDED_SOLAR_CAPACITY    17520 non-null  int64
 10  NON_BM_STOR                17520 non-null  int64
 11  PUMP_STORAGE_PUMPING       17520 non-null  int64
 12  SCOTTISH_TRANSFER          17520 non-null  int64
 13  IFA_FLOW                   17520 non-null  int64
 14  IFA2_FLOW                  17520 non-null  int64
 15  BRITNED_FLOW               17520 non-null  int64
 16  MOYLE_FLOW                 17520 non-null  int64
 17  EAST_WEST_FLOW             17520 non-null  int64
 18  NEMO_FLOW                  17520 non-null  int64
 19  NSL_FLOW                   17520 non-null  int64
 20  ELECLINK_FLOW              17520 non-null  int64
 21  VIKING_FLOW                17520 non-null  int64
 22  GREENLINK_FLOW             17520 non-null  int64
dtypes: datetime64[ns, UTC](1), datetime64[ns](1), int64(21)
memory usage: 3.1 MB

In [82]:
processed_data = raw_data_df.copy()

processed_data.to_csv("/content/gridflow_2025_processed_data.csv", index =False)

# NOTES


**Data Exploration and Time Handling**


- Loaded the NESO Historic Demand Data for 2025. This included 17520 30min observations


*   Confirmed that there were no missing values in the raw dataset
*   Reviewed the Key NESO Concepts (website):
    - National Demand (ND): GB metered genreation requirement. Excludes station load, pumped storage pumping and interconnector exports.
    - Transmission System Demand (TSD): ND plus the additional requirements including station load, pumped storage pumping and interconnector exports
    - Embedded win/solar: Estiamted distribution connected generation, not fully visible through transmission level metering.
* Confirmed Settelment Period 1 is equal to 00:00 - 00:30, meaning 48 30min periods in one 24 hr day.

* Identified daylight saving (DST) exceptions:
    - 30/03/25 = 46 settlement periods (spring)
    - 26/10/25 = 50 settlement periods (autumn)

* Naive local time would have been unsuitable because DST can create repeated local times

* Created a continuous UTC timefram (MODEL_TIME) that progresses in 30min intervals.

* Retained SETTLEMENT_DATE and SETTLEMENT_PERIOD

* Verified that the UTC timeline is continuous on the days mentioned above